**Hanteringsanvisning for**

**Nuvaxovid XBB1.5**

**- vaccin mot covid-19**

**Novavax**

**Material: Se Artikellista for**

**rekommenderade produkter vid**

**vaccination mot covid-19**

**Kontrollera noggrant att du anvander ratt material**

**1. Hantering fore anvandning**

2. Transporteras kylt (2-8^ C).

3. F\(\ddot{\rm o}\)rvaras i kylskap (2-8^ C), far ej frysas.

4. Oppnad injektionsflaska har en hallbarhet pa 9 manader vid

forvaring i kylskap (2-8^ C). Se tryckt utgangsdatum.

5. Punkterad injektionsflaska ska

anvandas inom 6 timmar (2-25^ C),

efter denna idsperiod ska

produkten kasseras. Stall inte

tillbaka den i kylskapet.

6. F\(\ddot{\rm o}\)rvara injektionsflaskoma i

ytterkartongen da vaccinet ar

liuskansligt.

**Punkterad injektionsflaska ska**

**anvandas inom 6 timmar**

2. Vaccinet ar fardigtt for**

**anvandning (ska_inte spadas_)

3. Injektionsflaskan innehaller

motsvarande 5 doser a 0,5ml. Om

kvarvarande mangd vaccin racker

till ytterligare fulla doser sa kan det

iordningstallas och administreras.

**Uppdaterat fran f\(\ddot{\rm o}\)regaende version**

**2023-11-29: Uppdaterat vaccin Nuvaxovid XBB1.5 Antal doser i en injektionsflaska**

**andrat.**

Tidigare versionshistorik

2023-07-26 Redaktionella andringar. Byte av l\(\ddot{\rm a}\)nk.

2023-06-16 Redaktionella andringar. Byte av l\(\ddot{\rm a}\)nk.

2022-03-07 Ny hantringsanvisning

4. V\(\ddot{\rm o}\)and injektionsflaskan forskitgit.

Far ej skkas!

5. Kontrollera att v\(\ddot{\rm o}\)stkan ar farglos till

svagt gul, klar dispersion. Inga

synliga partiklar och/ eller

missf\(\ddot{\rm a}\)argning far f\(\ddot{\rm o}\)rekomma.

**3. Berendning av enskilda 0,5 ml**

**doser av Nuvaxovid**

Material: Spruta 1 ml med fast kanyl ( 23G

eller25G) och lag d\(\ddot{\